### ISSUE TITLE
Chat para desarrolladores del simulador de Yugioh.

### ISSUE THREAD

**Issue by PixelatedProphet** [termitaklk/edopro-live-viewer#1]
Estamos interesados ​​en su proyecto y nos gustaría que se una a nuestro chat de desarrollo. Tenemos desarrolladores de Salvation, Edopro, Dueling Book, Dueling Nexus y otros aquí.

https://discord.gg/wUjrTS4

**Comment by termitaklk** [comment]
Thanks
